version:  '3'
services:
  r-notebook:
    environment:
      - JUPYTER_ENABLE_LAB=yes
    build:
      context: .
      dockerfile: ./Dockerfile
    image: r-notebook
    volumes:
      - ./work:/home/jovyan/work
    ports:
      - 8888:8888
    command: start-notebook.sh --NotebookApp.password=sha1:3881d88961d7:8993b582e2f5a77babe4a108031298a12a6c714a
